# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://zirukraine.com
title: Zir Ukraine AR aerial awareness system for ground troops
email: zirukraine+info@gmail.com
author: Zir Ukraine
description: > # "Write an awesome description for your new site here. 
  AR friend or foe awareness system/tactical map for ground troops, using thermal and visible images from programmatically piloted quadcopter
copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/ZirUkraine
  - title: linkedin
    url: https://linkedin.com/zirukraine
  - title: email
    url: mailto:zirukraine+info@gmail.com
